### ISSUE TITLE
crash once enter all data

### ISSUE THREAD

**Issue by nf24eg** [XavierisOP/YouTube-video-downloader-with-Python#1]
hello, I've downloaded everything and all working well, one I fill the date, location to save, download channel, and channel address the window crash

**Comment by SabbirXavier** [comment]
Hello,

Thank you for reaching out and for trying out the project. It's great to hear that everything is working well for you with one small issue. It appears that you're experiencing a crash when filling in the date, location to save, download channel, and channel address.

The issue you're facing might be due to the missing `pytube` library, as you mentioned. To resolve this, you can indeed try running the following command:

```bash
pip install pytube
```

Downlaod Executable File [YotubeDowloadManagerV2](https://github.com/XavierisOP/YouTube-video-downloader-with-Python/releases/download/youtube-downloader/YouTubeDownloadManager.exe)

**Comment by nf24eg** [comment]
Hello, many thanks for your reply, I installed the missing pip install pytube
But now I’m getting this
“[INPUT] Enter your choice! » 2

Download From a PlayList -
[INPUT] Enter a Playlist URL! » https://www.youtube.com/watch?v=rYEDA3JcQqw&list=PL6aXn5OcbJVUc0x0tUojhcrRf80hScGai
Total Videos 8

Download PlayList Bulk or Selective -
[01] » Downlaod all Videos From Playlist
[02] » Downlaod Recently Uploaded Videos From Playlist
[INPUT] Enter your choice! » 1
Traceback (most recent call last):
  File "pytube\__main__.py", line 341, in title
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 77, in <module>
  File "pytube\__main__.py", line 346, in title
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=rYEDA3JcQqw. Please file a bug report at https://github.com/pytube/pytube

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 80, in <module>
NameError: name 'VideoUnavailable' is not defined
[7952] Failed to execute script 'main' due to unhandled exception!”

**Comment by nf24eg** [comment]
I updated all the pip but I'm getting this error  (the link to youtube is just for test)
Enter a Directiory where all video will be download! » C:\Users\XXX\youtube

CHOOSE THE OPTION ACCORDING TO YOUR NEED -
[01] » Downlaod a Single Video
[02] » Download From PlayList
[03] » Download From a Channel
[INPUT] Enter your choice! » 01

Download for a Single Video -
[INPUT] Enter a video URL! » https://www.youtube.com/watch?v=XsVtSPgaRzI
Traceback (most recent call last):
  File "pytube\__main__.py", line 341, in title
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 45, in <module>
  File "pytube\__main__.py", line 346, in title
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=XsVtSPgaRzI. Please file a bug report at https://github.com/pytube/pytube
[14056] Failed to execute script 'main' due to unhandled exception!

**Comment by SabbirXavier** [comment]
I wanted to provide a quick update on our program. 
Currently, I'm occupied with other commitments, and I've made essential fixes. 
Check it out New release......
